// Code generated by "stringer -type=Type -trimprefix=Type"; DO NOT EDIT.

package value

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TypeInt-0]
	_ = x[TypeFloat-1]
	_ = x[TypeBoolean-2]
	_ = x[TypeChar-3]
	_ = x[TypeNil-4]
	_ = x[TypeFunc-5]
	_ = x[TypePointer-6]
}

const _Type_name = "IntFloatBooleanCharNilFuncPointer"

var _Type_index = [...]uint8{0, 3, 8, 15, 19, 22, 26, 33}

func (i Type) String() string {
	if i >= Type(len(_Type_index)-1) {
		return "Type(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Type_name[_Type_index[i]:_Type_index[i+1]]
}
