// Code generated by "stringer -type=Type -trimprefix=Type"; DO NOT EDIT.

package value

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TypeNumber-0]
	_ = x[TypeBoolean-1]
	_ = x[TypeChar-2]
	_ = x[TypeString-3]
}

const _Type_name = "NumberBooleanCharString"

var _Type_index = [...]uint8{0, 6, 13, 17, 23}

func (i Type) String() string {
	if i >= Type(len(_Type_index)-1) {
		return "Type(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Type_name[_Type_index[i]:_Type_index[i+1]]
}
